### ISSUE TITLE
Make destructive actions opt-in

### ISSUE THREAD

**Issue by wellsjo** [littlstar/s3-lambda#45]
The default behavior of map/reduce/filter is replacing files in-line. I don't want someone accidentally destroying their data.

- make destructive actions opt-in (not sure how to handle this yet)
- check that output is not the same prefix as the context

**Comment by schmod** [comment]
Yeah... I'm **really** glad I read the documentation first.

**Comment by wellsjo** [comment]
ok this has been addressed / published in `5.1.0`

**Comment by schmod** [comment]
This should probably be published as `6.0.0`, given that it's an API change.

**Comment by wellsjo** [comment]
@schmod Yeah I see now in npm's documentation that you should major release for breaking backwards compatibility. That's my bad, but I already released it. Should I go ahead and release 6 you think?
