### ISSUE TITLE
working with minio

### ISSUE THREAD

**Issue by jgranduel** [littlstar/s3-lambda#46]
Hi, 
does s3-lambda work with minio? if yes, could you provide an example? how to set another endpoint?
BTW, is there a reason why the API is a bit different from minio-js (accessKey vs accessKeyId, secretKey vs  secretAccessKey)?
Thanks
Best regards

**Comment by wellsjo** [comment]
s3-lambda is currently only built to work with AWS S3, although I'd be happy to abstract the code to work with other backends. S3 has a few quirks in the way it works so that this will be a pretty significant code change.
